# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f1af19097511a82a788f9a59db114e6"
name = "wishlisttestx"
handle = "wishlisttestx"
application_url = "https://mounting-services-eugene-corners.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "coes-functions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_products"

[auth]
redirect_urls = [
  "https://mounting-services-eugene-corners.trycloudflare.com/auth/callback",
  "https://mounting-services-eugene-corners.trycloudflare.com/auth/shopify/callback",
  "https://mounting-services-eugene-corners.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://mounting-services-eugene-corners.trycloudflare.com"
subpath = "my-proxy"
prefix = "apps"

[pos]
embedded = false
